apiVersion: apps/v1
kind: Deployment # a type of resourse 
metadata:
  name: mongodb-deployment # the name of this resource
  labels:
    app: mongodb # a label of this deployment.
spec: # specification for deployment
  replicas: 1 # to create one replica
  selector:
    matchLabels:
      app: mongodb # to connect to pod for control state of pods in deployment
  template:
    metadata:
      labels:
        app: mongodb # a label for connecting service to pod
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          valueFrom: 
            secretKeyRef: # a reference to mongo-secret.yaml
             name: mongodb-secret # a name of entity
             key: mongo-root-username # a name of value
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:       
            secretKeyRef:
             name: mongodb-secret
             key: mongo-root-password
--- # multiple documents in one file
apiVersion: v1
kind: Service # service kind
metadata:
  name: mongodb-service # name of service
spec:
  selector: # to connect to Pod through label "mongodb"
    app: mongodb
  ports: # expose a port in service
    - protocol: TCP
      port: 27017 # port of service
      targetPort: 27017 # conteinerPort of deployment
          