apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME # user name takes from mongo-secret
          valueFrom:
            secretKeyRef: # reference to mongo-secret
              name: mongodb-secret # name of resource
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef: # reference to mongo-config map
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service # service kind
metadata:
  name: mongo-express-service # name of service
spec:
  selector: # to connect to Pod through label "mongodb"
    app: mongo-express
  type: LoadBalancer # assign service an external IP and so excepts external request
  ports: # expose a port in service
    - protocol: TCP
      port: 8081 # port of service
      targetPort: 8081 # conteinerPort of deployment
      nodePort: 30000 # port for external IP 